kernelsu-objs := core/init.o

kernelsu-objs += feature/kernel_umount.o
kernelsu-objs += feature/sulog.o
kernelsu-objs += feature/sucompat.o

kernelsu-objs += hook/setuid_hook.o

kernelsu-objs += infra/file_wrapper.o
kernelsu-objs += infra/event_queue.o
kernelsu-objs += infra/seccomp_cache.o
kernelsu-objs += infra/su_mount_ns.o
kernelsu-objs += infra/symbol_resolver.o

ifneq ($(CONFIG_KSU_DISABLE_MANAGER),y)
kernelsu-objs += manager/apk_sign.o
kernelsu-objs += manager/pkg_observer.o
kernelsu-objs += manager/throne_tracker.o
endif

kernelsu-objs += policy/allowlist.o
kernelsu-objs += policy/app_profile.o
kernelsu-objs += policy/feature.o

kernelsu-objs += runtime/boot_event.o
kernelsu-objs += runtime/ksud_integration.o

kernelsu-objs += selinux/selinux.o
kernelsu-objs += selinux/rules.o
kernelsu-objs += selinux/sepolicy.o

kernelsu-objs += sulog/event.o
kernelsu-objs += sulog/fd.o

kernelsu-objs += supercall/dispatch.o
kernelsu-objs += supercall/perm.o
kernelsu-objs += supercall/supercall.o

kernelsu-objs += feature/adb_root.o

kernelsu-objs += feature/selinux_hide.o

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_KSU_DISABLE_MANAGER),y)
ccflags-y += -DCONFIG_KSU_DISABLE_MANAGER=1
endif
ifeq ($(CONFIG_KSU_DISABLE_POLICY),y)
ccflags-y += -DCONFIG_KSU_DISABLE_POLICY=1
endif
ifeq ($(CONFIG_KSU_DEBUG),y)
ccflags-y += -DCONFIG_KSU_DEBUG=1
endif
endif

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifneq ($(KBUILD_EXTMOD),)
# 6.18 exports the external module source as srcroot when M/MO are used.
ifneq ($(srcroot),)
KSU_KERNEL_DIR := $(srcroot)
endif
endif
ifndef KSU_KERNEL_DIR
ifeq ($(filter /%,$(src)),)
KSU_KERNEL_DIR := $(srctree)/$(src)
else
KSU_KERNEL_DIR := $(src)
endif
endif

ccflags-y += -I$(KSU_KERNEL_DIR) -I$(KSU_KERNEL_DIR)/include

obj-$(CONFIG_KSU) += kernelsu.o

KSU_NEW_DCACHE_FLUSH := $(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h ; echo $$?)
$(info -- KSU_NEW_DCACHE_FLUSH: $(KSU_NEW_DCACHE_FLUSH))

obj-$(CONFIG_KPM) += kpm/compact.o
obj-$(CONFIG_KPM) += kpm/kpm.o
obj-$(CONFIG_KPM) += kpm/super_access.o

# KernelPatch engine graft (real KPM runtime, native supercall on syscall 45)
KP_DIR := $(KSU_KERNEL_DIR)/kpm/kp
KP_INCLUDES := -I$(KP_DIR)/include -I$(KP_DIR)/kernel_base/patch/include/uapi \
               -I$(KP_DIR)/kernel_base/patch/include -I$(KP_DIR)/kernel_base/include
KP_VERSION_DEFS := -DKP_LKM_MAJOR=0 -DKP_LKM_MINOR=13 -DKP_LKM_PATCH=9 -DANDROID
KP_ALLFLAGS := $(KP_INCLUDES) $(KP_VERSION_DEFS) -DKP_NEW_DCACHE_FLUSH=$(KSU_NEW_DCACHE_FLUSH)

obj-$(CONFIG_KPM) += kpm/kp/kpm/module.o
obj-$(CONFIG_KPM) += kpm/kp/kpm/relo.o
obj-$(CONFIG_KPM) += kpm/kp/kpm/insn.o
obj-$(CONFIG_KPM) += kpm/kp/kpm/symbols.o
obj-$(CONFIG_KPM) += kpm/kp/kpm/kpm.o
obj-$(CONFIG_KPM) += kpm/kp/hook/hook_engine.o
obj-$(CONFIG_KPM) += kpm/kp/hook/hook_runtime.o
obj-$(CONFIG_KPM) += kpm/kp/infra/patch_memory.o
obj-$(CONFIG_KPM) += kpm/kp/infra/syscall_table.o
obj-$(CONFIG_KPM) += kpm/kp/infra/symbol_resolver.o
obj-$(CONFIG_KPM) += kpm/kp/supercall/supercall.o
obj-$(CONFIG_KPM) += kpm/kp/supercall/dispatch.o

CFLAGS_kpm/kp/kpm/module.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/kpm/relo.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/kpm/insn.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/kpm/symbols.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/kpm/kpm.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kpm.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/hook/hook_runtime.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/infra/patch_memory.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/infra/syscall_table.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/infra/symbol_resolver.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/supercall/supercall.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/supercall/dispatch.o += $(KP_ALLFLAGS)

# hook_engine includes the bare-metal hook chain engine: exempt from CFI/SCS,
# drop PAC + LTO, keep BTI (trampoline branches into _transitN must be valid).
CFLAGS_kpm/kp/hook/hook_engine.o += $(KP_ALLFLAGS)
CFLAGS_kpm/kp/hook/hook_engine.o += -fno-sanitize=cfi -fno-stack-protector -fno-jump-tables
CFLAGS_kpm/kp/hook/hook_engine.o += -fno-unwind-tables -fno-asynchronous-unwind-tables
CFLAGS_kpm/kp/hook/hook_engine.o += -std=gnu11 -Wno-strict-prototypes
CFLAGS_kpm/kp/hook/hook_engine.o += -fno-lto
CFLAGS_kpm/kp/hook/hook_engine.o += -fno-sanitize=shadow-call-stack
CFLAGS_kpm/kp/hook/hook_engine.o += -mbranch-protection=bti

ifeq ($(CONFIG_KPM), y)
$(info -- KPM is enabled)
else
$(info -- KPM is disabled)
endif

KSU_VERSION := 32601
$(info -- KernelSU version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)


ifndef KSU_EXPECTED_SIZE
KSU_EXPECTED_SIZE := 0x033b
endif

ifndef KSU_EXPECTED_HASH
KSU_EXPECTED_HASH := c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
$(info -- KernelSU Manager package name: $(KSU_MANAGER_PACKAGE))
endif

$(info -- KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
$(info -- KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))

ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"

ifdef KSU_EXPECTED_SIZE2
ifndef KSU_EXPECTED_HASH2
$(error KSU_EXPECTED_HASH2 must be set when KSU_EXPECTED_SIZE2 is set)
endif
ccflags-y += -DEXPECTED_SIZE2=$(KSU_EXPECTED_SIZE2)
ccflags-y += -DEXPECTED_HASH2=\"$(KSU_EXPECTED_HASH2)\"
$(info -- KernelSU Manager signature size2: $(KSU_EXPECTED_SIZE2))
$(info -- KernelSU Manager signature hash2: $(KSU_EXPECTED_HASH2))
endif

ccflags-y += -DKSU_NEW_DCACHE_FLUSH=$(KSU_NEW_DCACHE_FLUSH)

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function

# Keep a new line here!! Because someone may append config
